export type LandingLocale = "es" | "en";

export const landingCopy = {
  es: {
    nav: {
      platform: "Plataforma",
      modules: "Módulos",
      levels: "Niveles",
      pricing: "Precios",
      resources: "Recursos",
      login: "Iniciar sesión",
      demo: "Solicitar demo",
    },
    hero: {
      badge: "SIS + LMS para escuelas modernas",
      titleA: "La gestión escolar,",
      titleB: "simplificada.",
      subtitle: "Sistema todo-en-uno para escuelas modernas. Desde guardería hasta universidad, Educore conecta administración, aprendizaje, evaluación, comunicación y pagos en una sola plataforma.",
      demo: "Solicitar demo gratis",
      video: "Ver cómo funciona",
      trust: "Demo guiada · Migración asistida · Soporte en español",
    },
    trust: {
      label: "Diseñado para equipos escolares que necesitan orden y visibilidad",
      schools: ["Dirección", "Control escolar", "Docentes", "Familias", "Administración", "Coordinación"],
    },
    benefits: {
      eyebrow: "Por qué Educore",
      title: "Una plataforma que entiende cómo funciona tu escuela.",
      items: [
        {
          title: "Plataforma todo-en-uno",
          text: "Gestión, aprendizaje, evaluación y comunicación en un solo lugar. Sin migrar entre apps.",
          stat: "Flujos conectados",
        },
        {
          title: "Automatización inteligente",
          text: "Boletas, asistencia, recordatorios y reportes generados automáticamente con IA.",
          stat: "Menos captura manual",
        },
        {
          title: "Ahorro de tiempo real",
          text: "Lo que antes tomaba horas, ahora toma minutos. Tu equipo dedicado a lo importante.",
          stat: "Cierre diario más claro",
        },
      ],
    },
    services: {
      eyebrow: "Servicios",
      title: "Todo lo que tu escuela opera, en un solo sistema.",
      intro: "Educore cubre la operación diaria de guardería, kinder y primaria; y deja listo el camino para secundaria, preparatoria y universidad.",
      available: "Disponible",
      soon: "Próximo",
      items: [
        { title: "Alumnos y expedientes", text: "Altas, datos familiares, documentos, historial académico y seguimiento por grupo.", status: "available" },
        { title: "Profesores y grupos", text: "Gestión de docentes, asignaciones, grupos, materias y ciclos escolares.", status: "available" },
        { title: "Asistencia y horarios", text: "Registro diario, retardos, justificantes, horarios por grupo y alertas operativas.", status: "available" },
        { title: "Pagos y recibos", text: "Cargos, pagos manuales, historial, recibos y visibilidad para familias.", status: "available" },
        { title: "Boletas y documentos", text: "Report cards, expedientes digitales, consentimientos y archivos escolares.", status: "available" },
        { title: "Comunicación escolar", text: "Mensajes, anuncios, notificaciones y comunicación con padres y docentes.", status: "available" },
        { title: "Reportes y analytics", text: "Indicadores de asistencia, desempeño, cobranza y salud operativa.", status: "available" },
        { title: "Database Admin seguro", text: "Exploración de tablas y datos con permisos de Super Admin y protección de tenant.", status: "available" },
        { title: "Migración asistida", text: "Acompañamiento para mover escuelas desde hojas de cálculo o sistemas previos.", status: "available" },
        { title: "IA para evaluación", text: "Detección de riesgo académico, apoyo en reportes y análisis de desempeño.", status: "soon" },
        { title: "Credenciales y acceso QR", text: "Control de acceso, credenciales digitales y flujos de entrada/salida.", status: "soon" },
        { title: "Multi-campus avanzado", text: "Operación para redes escolares, campus y niveles superiores.", status: "soon" },
      ],
    },
    modules: {
      eyebrow: "Módulos",
      title: "Cuatro módulos. Una experiencia.",
      intro: "Activa solo los que necesites. Todos están conectados, comparten datos y se sienten como uno solo.",
      items: [
        {
          title: "Administración",
          text: "Inscripciones, pagos, expedientes y reportes en automático.",
          features: ["Cobranza automática", "Expedientes digitales", "Reportes SEP", "Control de acceso"],
        },
        {
          title: "Aprendizaje",
          text: "Aulas virtuales, contenido y entrega de tareas integradas.",
          features: ["Aula virtual", "Biblioteca digital", "Tareas y rúbricas", "Asistencia"],
        },
        {
          title: "Evaluación",
          text: "Calificaciones, boletas y análisis de desempeño con IA.",
          features: ["Boletas automáticas", "Análisis con IA", "Reportes a padres", "Predicción de riesgo"],
        },
        {
          title: "Comunicación",
          text: "Chat, anuncios, citas y notificaciones unificadas.",
          features: ["Chat por grupo", "Anuncios masivos", "App para padres", "Citas y reuniones"],
        },
      ],
    },
    levels: {
      eyebrow: "Niveles educativos",
      title: "Una plataforma que crece con tu institución.",
      intro: "No necesitas cambiar de sistema conforme creces. Educore acompaña cada etapa escolar con módulos conectados y datos históricos.",
      active: "Disponible",
      upcoming: "Próximamente",
      items: [
        ["Guardería", "👶", "active"],
        ["Kinder", "🎨", "active"],
        ["Primaria", "📘", "active"],
        ["Secundaria", "🧪", "soon"],
        ["Secundaria técnica", "⚙️", "soon"],
        ["Preparatoria", "🎓", "soon"],
        ["Preparatoria técnica", "🛠️", "soon"],
        ["Universidad", "🏛️", "soon"],
      ],
    },
    comparison: {
      eyebrow: "Comparativa",
      title: "Por qué las escuelas eligen Educore",
      headers: ["Característica", "Educore", "SIS tradicional", "LMS aislado"],
      rows: [
        ["Plataforma todo-en-uno (SIS + LMS)", true, false, false],
        ["Automatización de procesos", true, false, true],
        ["App nativa para padres", true, true, false],
        ["Soporte en español", true, false, false],
        ["Migración asistida", true, false, false],
        ["Reportes SEP automáticos", true, false, false],
        ["Integraciones (Google, Microsoft, etc)", true, true, true],
        ["Precio por alumno escalable", true, true, false],
      ],
    },
    integrations: {
      eyebrow: "Integraciones",
      title: "Conecta con las herramientas que ya usas.",
      text: "Educore está pensado para convivir con herramientas escolares comunes como Google Workspace, Microsoft 365, videollamadas, pagos y recursos educativos.",
      stats: ["Google y Microsoft", "API preparada", "SSO previsto"],
    },
    testimonials: {
      eyebrow: "Escenarios",
      title: "Cómo se siente Educore dentro de una operación escolar real.",
      items: [
        ["Dirección escolar", "Visión institucional", "El equipo directivo ve asistencia, pagos, comunicación y avance académico sin pedir reportes por separado."],
        ["Control escolar", "Operación diaria", "Inscripciones, expedientes, grupos y boletas viven en un mismo flujo, con menos captura repetida."],
        ["Coordinación académica", "Seguimiento docente", "Profesores y familias trabajan sobre la misma información, con historial claro por alumno y grupo."],
      ],
    },
    cta: {
      eyebrow: "Empieza hoy",
      title: "Tu escuela merece una mejor plataforma.",
      text: "Migración asistida. Equipo dedicado. Acompañamiento desde el primer mes.",
      demo: "Solicitar demo gratuita",
      sales: "Hablar con ventas",
      caption: "30 minutos · En español · Enfoque consultivo",
    },
    footer: {
      tagline: "El sistema integral que conecta toda tu escuela. Hecho en México, para Latinoamérica.",
      platform: ["Administración", "Aprendizaje", "Evaluación", "Comunicación", "IA Educore"],
      solutions: ["Para directores", "Para profesores", "Para padres", "Para alumnos", "Por nivel educativo"],
      resources: ["Centro de ayuda", "Blog", "Webinars", "Casos de éxito", "API y docs"],
      company: ["Sobre Educore", "Carreras", "Contacto", "Prensa", "Partners"],
    },
    form: {
      title: "Solicitar demo",
      subtitle: "Cuéntanos de tu institución y te contactamos para una demo guiada.",
      name: "Nombre",
      email: "Email institucional",
      school: "Nombre de la escuela",
      role: "Cargo",
      students: "# alumnos",
      message: "Mensaje opcional",
      send: "Enviar solicitud",
      success: "Solicitud preparada. Te contactaremos pronto.",
    },
  },
  en: {
    nav: {
      platform: "Platform",
      modules: "Modules",
      levels: "Levels",
      pricing: "Pricing",
      resources: "Resources",
      login: "Sign in",
      demo: "Request demo",
    },
    hero: {
      badge: "SIS + LMS for modern schools",
      titleA: "School management,",
      titleB: "simplified.",
      subtitle: "An all-in-one system for modern schools. From daycare to university, Educore connects administration, learning, assessment, communication, and payments.",
      demo: "Request free demo",
      video: "See how it works",
      trust: "Guided demo · Assisted migration · Spanish support",
    },
    trust: {
      label: "Designed for school teams that need order and visibility",
      schools: ["Leadership", "Admissions", "Teachers", "Families", "Administration", "Coordination"],
    },
    benefits: {
      eyebrow: "Why Educore",
      title: "A platform that understands how your school works.",
      items: [
        { title: "All-in-one platform", text: "Management, learning, assessment, and communication in one place.", stat: "Connected workflows" },
        { title: "Smart automation", text: "Report cards, attendance, reminders, and reports move through guided flows.", stat: "Less manual capture" },
        { title: "Real time savings", text: "Daily school work becomes easier to coordinate and review.", stat: "Clearer daily close" },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "Everything your school runs, in one system.",
      intro: "Educore covers daily operations for daycare, kindergarten and elementary school, while preparing the path for middle school, high school and university.",
      available: "Available",
      soon: "Soon",
      items: [
        { title: "Students and records", text: "Enrollment, family data, documents, academic history and group follow-up.", status: "available" },
        { title: "Teachers and groups", text: "Teacher management, assignments, groups, subjects and school years.", status: "available" },
        { title: "Attendance and schedules", text: "Daily attendance, delays, justifications, group schedules and alerts.", status: "available" },
        { title: "Payments and receipts", text: "Charges, manual payments, history, receipts and family visibility.", status: "available" },
        { title: "Report cards and documents", text: "Report cards, digital records, consents and school files.", status: "available" },
        { title: "School communication", text: "Messages, announcements, notifications and parent-teacher communication.", status: "available" },
        { title: "Reports and analytics", text: "Attendance, performance, billing and operational health indicators.", status: "available" },
        { title: "Secure Database Admin", text: "Table and data exploration with Super Admin permissions and tenant protection.", status: "available" },
        { title: "Assisted migration", text: "Guided migration from spreadsheets or previous school systems.", status: "available" },
        { title: "AI for assessment", text: "Academic risk detection, report support and performance analysis.", status: "soon" },
        { title: "Credentials and QR access", text: "Access control, digital credentials and entry/exit workflows.", status: "soon" },
        { title: "Advanced multi-campus", text: "Operations for school networks, campuses and higher education levels.", status: "soon" },
      ],
    },
    modules: {
      eyebrow: "Modules",
      title: "Four modules. One experience.",
      intro: "Activate only what you need. Everything is connected and feels like a single product.",
      items: [
        { title: "Administration", text: "Enrollment, payments, records, and reports on autopilot.", features: ["Automated billing", "Digital records", "Official reports", "Access control"] },
        { title: "Learning", text: "Virtual classrooms, content, and assignments in one place.", features: ["Virtual classroom", "Digital library", "Assignments", "Attendance"] },
        { title: "Assessment", text: "Grades, report cards, and AI-powered performance analysis.", features: ["Automatic report cards", "AI analysis", "Parent reports", "Risk prediction"] },
        { title: "Communication", text: "Chat, announcements, meetings, and notifications unified.", features: ["Group chat", "Mass announcements", "Parent app", "Meetings"] },
      ],
    },
    levels: {
      eyebrow: "Education levels",
      title: "A platform that grows with your institution.",
      intro: "No need to switch systems as you grow. Educore follows every stage with connected modules and historical data.",
      active: "Available",
      upcoming: "Coming soon",
      items: [["Daycare", "👶", "active"], ["Kindergarten", "🎨", "active"], ["Elementary", "📘", "active"], ["Middle school", "🧪", "soon"], ["Technical middle school", "⚙️", "soon"], ["High school", "🎓", "soon"], ["Technical high school", "🛠️", "soon"], ["University", "🏛️", "soon"]],
    },
    comparison: {
      eyebrow: "Comparison",
      title: "Why schools choose Educore",
      headers: ["Feature", "Educore", "Traditional SIS", "Isolated LMS"],
      rows: [
        ["All-in-one platform (SIS + LMS)", true, false, false],
        ["Process automation", true, false, true],
        ["Native parent app", true, true, false],
        ["Spanish support", true, false, false],
        ["Assisted migration", true, false, false],
        ["Automatic official reports", true, false, false],
        ["Integrations (Google, Microsoft, etc)", true, true, true],
        ["Scalable per-student pricing", true, true, false],
      ],
    },
    integrations: {
      eyebrow: "Integrations",
      title: "Connect the tools you already use.",
      text: "Educore is designed to work alongside common school tools like Google Workspace, Microsoft 365, video calls, payments, and learning resources.",
      stats: ["Google and Microsoft", "API prepared", "SSO planned"],
    },
    testimonials: {
      eyebrow: "Scenarios",
      title: "How Educore feels inside real school operations.",
      items: [
        ["School leadership", "Institutional visibility", "The leadership team sees attendance, payments, communication, and academics without asking for separate reports."],
        ["Admissions office", "Daily operations", "Enrollment, records, groups, and report cards live in one flow with less repeated capture."],
        ["Academic coordination", "Teacher follow-up", "Teachers and families work from the same information, with a clear history for every student and group."],
      ],
    },
    cta: {
      eyebrow: "Start today",
      title: "Your school deserves a better platform.",
      text: "Assisted migration. Dedicated team. Guidance from month one.",
      demo: "Request free demo",
      sales: "Talk to sales",
      caption: "30 minutes · In Spanish · Consultative focus",
    },
    footer: {
      tagline: "The all-in-one system that connects your whole school. Built in Mexico for Latin America.",
      platform: ["Administration", "Learning", "Assessment", "Communication", "Educore AI"],
      solutions: ["For directors", "For teachers", "For parents", "For students", "By education level"],
      resources: ["Help center", "Blog", "Webinars", "Success stories", "API and docs"],
      company: ["About Educore", "Careers", "Contact", "Press", "Partners"],
    },
    form: {
      title: "Request demo",
      subtitle: "Tell us about your institution and we will contact you for a guided demo.",
      name: "Name",
      email: "Institutional email",
      school: "School name",
      role: "Role",
      students: "# students",
      message: "Optional message",
      send: "Send request",
      success: "Request prepared. We will contact you soon.",
    },
  },
} as const;
